Course_work_22_04/Controllers/WorkResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Course_work_22_04.Models;




namespace Course_work_22_04.Controllers
{
    public class WorkResultController : Controller
    {

        // GET: Work


        FileContext db = new FileContext();

        private CryptionData GetCryptionData(List<ID_Key> ListId)
        {
            var data = new CryptionData();          
            
            if (ListId == null)
                return CryptionData.None;
            int fileId;
            try
            {
                fileId = ListId[0].Id;
            }
            catch
            {
                return CryptionData.None;
            }
            var file = db.GetById(fileId);
            if (file == null)
                return CryptionData.None;

            data.File = file;
            data.Shift = Convert.ToInt32(ListId[0].Key);
            return data;
        }

        [HttpPost]
        public ActionResult Download(string shift)
        {
            List<ID_Key> ListId = (List<ID_Key>)TempData["ListId"];
            var data = GetCryptionData(ListId);
            if (data == CryptionData.None)
                return RedirectToAction("Index", "Home");

            int iShift = int.Parse(shift);
            byte[] bytes;
            string fileType;
            string text;
            if (data.File.Name.EndsWith(".txt"))
            {
                fileType = "text/plain";
                text = Caesar.Shift(data.File.Text, iShift);
                bytes = TextService.GetTxtFileWithText(text);
            }
            else
            {
                fileType = "application/msword";
                text = Caesar.Shift(data.File.Text, iShift);
                bytes = TextService.GetDocFileWithText(text);
            }


            return File(bytes, fileType, data.File.Name);
        }
        public ActionResult Encrypt()
        {
            List<ID_Key> ListId = (List<ID_Key>)TempData["ListId"];
            var data = GetCryptionData(ListId);
            if (data == CryptionData.None)
                return RedirectToAction("Index", "Home");

            ViewBag.Key = data.Shift;
            ViewBag.Text = Caesar.Shift(data.File.Text, data.Shift); 
            TempData["ListId"] = ListId;
            return View();
        }

        public ActionResult Decryption()
        {
            List<ID_Key> ListId = (List<ID_Key>)TempData["ListId"];
            var data = GetCryptionData(ListId);
            if (data == CryptionData.None)
                return RedirectToAction("Index", "Home");

            ViewBag.Key = data.Shift;
            ViewBag.Text = Caesar.Shift(data.File.Text, -data.Shift); ;
            TempData["ListId"] = ListId;
            return View();
        }

        public ActionResult KeySearch()
        {
            List<ID_Key> ListId = (List<ID_Key>)TempData["ListId"];
            var data = GetCryptionData(ListId);
            if (data == CryptionData.None)
                return RedirectToAction("Index", "Home");

            ViewBag.Keys = Caesar.GetBestKey(data.File.Text);
            ViewBag.Text = data.File.Text;
            TempData["ListId"] = ListId;
            return View();
        }


    }
}

Course_work_22_04/Views/WorkResult/Decryption.cshtml
@{
    ViewBag.Title = "Decryption";
}
<div class="my-resume-area fix gray-bg pt-100 pb-100">
    <div class="container">
        <div class="my-resume">
            <div class="row ">
                <div class="col-xl-12 col-lg-12 col-md-12 col-12 pb-40">
                    <div class="my-resume-wrapper text-left">
                        <div class="my-resume-content">

                            <h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.25s">      Caesar <span>cipher.</span></h1>

                        </div>
                    </div>
                </div>

                <div class="container m-2 text-center">
                    <h2>Результаты расшифровки</h2><hr />
                    <h4>Текст был расшифрован с ключом <strong>@ViewBag.Key</strong></h4>
                    <div class="border p-2 mb-3 bg-white">
                        <p>@ViewBag.Text</p>
                    </div>
                    <h3 class="pb-2">Вы можете скачать результат:</h3>
                    @using (Html.BeginForm("Download", "Crypt", FormMethod.Post))
                    {
                        <input name="shift" type="hidden" value="@(-ViewBag.Key)">
                        <button class="btn btn-lg mt-auto" type="submit">Скачать</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Course_work_22_04/Views/WorkResult/Encrypt.cshtml
@{
    ViewBag.Title = "Encrypt";
}

<div class="my-resume-area fix gray-bg pt-100 pb-100">
    <div class="container">
        <div class="my-resume">
            <div class="row ">
                <div class="col-xl-12 col-lg-12 col-md-12 col-12 pb-40">
                    <div class="my-resume-wrapper text-left">
                        <div class="my-resume-content">

                            <h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.25s">      Caesar <span>cipher.</span></h1>

                        </div>
                    </div>
                </div>

                <div class="container m-2 text-center">
                    <h2>Результаты зашифровки</h2><hr />
                    <h4>Текст был зашифрован с ключом <strong>@ViewBag.Key</strong></h4>
                    <div class="border p-2 mb-3 bg-white">
                        <p>@ViewBag.Text</p>
                    </div>
                    <h3 class="pb-2">Вы можете скачать результат:</h3>
                    @using (Html.BeginForm("Download", "WorkResult", FormMethod.Post))
                    {

                        <input name="shift" type="hidden" value="@ViewBag.Key">
                        <button class="btn btn-lg mt-auto" type="submit">Скачать</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Course_work_22_04/Views/WorkResult/KeySearch.cshtml
@{
    ViewBag.Title = "KeySearch";
}

<div class="my-resume-area fix gray-bg pt-100 pb-100">
    <div class="container">
        <div class="my-resume">
            <div class="row ">
                <div class="col-xl-12 col-lg-12 col-md-12 col-12 pb-40">
                    <div class="my-resume-wrapper text-left">
                        <div class="my-resume-content">

                            <h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.25s">      Caesar <span>cipher.</span></h1>

                        </div>
                    </div>
                </div>

                <div class="container m-2 text-center">
                    <h2>Результаты поиска</h2><hr />
                    <h4>Наиболее подходящим ключом оказался <strong>@ViewBag.Keys[0]</strong></h4>
                    <div class="container">
                        <div class="row row-flex p-2">
                            <div class="col-md-1">
                                @ViewBag.Keys[0]
                            </div>
                            <div class="col m-block">
                                <p>@Course_work_22_04.Models.Caesar.Shift(ViewBag.Text, -ViewBag.Keys[0])</p>
                            </div>
                            <div class="col-md-1">
                                @using (Html.BeginForm("Download", "WorkResult", FormMethod.Post))
                                {
                                    <input name="shift" type="hidden" value="@(-ViewBag.Keys[0])">
                                    <button type="submit" class="btn btn-lg mt-auto">Dowload</button>
                                }
                            </div>
                        </div>
                    </div>

                    <h4>Другие варианты:</h4>
                    @for (int i = 1; i < ViewBag.Keys.Length; i++)
                    {
                        <div class="container">
                            <div class="row row-flex p-3">
                                <div class="col-md-1">
                                    @ViewBag.Keys[i]
                                </div>
                                <div class="col m-block">
                                    <p>@Course_work_22_04.Models.Caesar.Shift(ViewBag.Text, -ViewBag.Keys[i])</p>
                                </div>
                                <div class="col-md-1">
                                    @using (Html.BeginForm("Download", "WorkResult", FormMethod.Post))
                                    {
                                        <input name="shift" type="hidden" value="@(-ViewBag.Keys[i])">
                                        <button type="submit" class="btn btn-lg mt-auto">Dowload</button>
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>